fail-on-severity: moderate

comment-summary-in-pr: always

allow-licenses:
   - MIT
  - MIT-0
  - GPL-3.0
  - BSD-3-Clause
  - BSD-2-Clause
  - ISC
  - Apache-2.0
  - Zlib
fail-on-scopes:
  - development
  - runtime
  - unknown
